media:
  - name: diary_images
    label: 日記画像
    input: media/diary
    output: /media/diary
    categories: [image]
    rename: safe

content:
  - name: diary
    label: 日記
    type: collection
    path: _posts
    format: yaml-frontmatter
    exclude: ["README.md"]
    filename:
      template: "{year}-{month}-{day}-{primary}.md"
      field: false
    view:
      primary: title
      sort: date
      order: desc
    fields:
      - name: title
        label: タイトル
        type: string
        required: true
      - name: body
        label: 本文
        type: rich-text
        required: true
        options:
          format: markdown
          media: diary_images
          switcher: true

settings:
  commit:
    templates:
      create: "日記を追加: {filename}"
      update: "日記を更新: {filename}"
      delete: "日記を削除: {filename}"
      rename: "日記を改名: {oldPath} -> {newPath}"
